final Map<String, String> arSA = {
  ""        : "",
  "lectures": "العلماء وطلاب العلم",
  "books": "الكتب",
  "saved": "تم الحفظ: ",
  "open_pdf": "افتح PDF",
  "delete": "حذف",
  "no_bookmarks!": "لا إرسال!",
  "no_comments": "لا تعليق",
  "bookmark": "المرجعية",
  "comment": "تعليق",
  "downloading!": "جارى التحميل!",
  "file_is_downloaded_ready_to_open": "ملف يتم تحميلها على استعداد لفتح",
  "download": "تحميل",
  "loading": "جار التحميل",
  "failed": "فشل",
  "open": "افتح",
  "bookmarked!": "إشارة مرجعية!",
  "removed_bookmark!": "إزالة المفضلة!",
  "add_comment_to_this_page": "إضافة تعليق على هذه الصفحة",
  "save": "حفظ",
  "question_and_answer": "سؤال وجواب",
  "adjust_speed": "ضبط السرعة",
  "adjust_volume": "ضبط مستوى الصوت",
  "broadcast": "الإذاعة",
  "pause": "وقفة",
  "play": "تشغيل",
  "next": "التالي",
  "stop": "قف",
  "previous": "السابق",
  "please_download_file_first": "يُرجى تنزيل الملف أولاً",
  "about_shikh": "ترجمة الشيخ",
  "speech": "خطاب",
  "no_records_currently_added": "لم يتم العثور على أي سجلات. سيساعد الاتصال بالإنترنت في استرداد أحدث السجلات في هذه الفئة!",
  "texts": "الفوائد المنتقاة",
  "search": "يبحث",
  ":": ":",
  ".": ".",
  "0": "٠",
  "1": "١",
  "2": "٢",
  "3": "٣",
  "4": "٤",
  "5": "٥",
  "6": "٦",
  "7": "٧",
  "8": "٨",
  "9": "٩",
};