name: bestnation
description: Best Nation
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #  cupertino_icons: ^1.0.0

  firebase_core:                "^2.15.0"
  cloud_firestore:              "^4.8.4"
  firebase_analytics:           "^10.4.4"
  get:                          "^4.6.5"
  permission_handler:           "^10.4.3"
#  easy_localization:            "^3.0.2"   # Localise app lang
  flutter_staggered_animations: "^1.1.1" # Display grid with animation
#  percent_indicator:            "^3.0.1"
#  font_awesome_flutter:         "^9.0.0"
  dio:                          "^4.0.0"
  path_provider:                 "^2.1.0"
#  flutter_pdfview:              "^1.2.1"
  just_audio:                   "^0.9.34"
#  share:                        "^2.0.0" # Share files with others
  flutter_inappwebview:          "^5.7.2+3" # Open webpage for live stream
#  url_launcher:                 "^6.0.0"
  sqflite:                      "^2.3.0"
  flutter_xlider:               "^3.5.0"
  font_awesome_flutter:         "^10.5.0"
  progress_state_button:        "^1.0.4"


dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: ^0.9.0


flutter_launcher_name:
  name: "خير أمة"

flutter_icons:
  image_path: 'assets/brand/lunch_icon.jpg'
  android: true
  ios: true

flutter:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf

    - family: UthmanTahaNaskh
      fonts:
        - asset: assets/fonts/uthman_taha_naskh/Uthman-Taha-Naskh-Regular.ttf
        - asset: assets/fonts/uthman_taha_naskh/Uthman-Taha-Naskh-Bold.ttf

  uses-material-design: true

  assets:
    - assets/brand/
    - assets/langs/



