name: bestnation
description: Best Nation
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  cupertino_icons: ^1.0.0

  firebase_core:                "^1.0.0"
  cloud_firestore:              "^1.0.0"
  firebase_analytics:           "^7.1.0"
#
  easy_localization:            "^3.0.0"   # Localise app lang
  flutter_staggered_animations: "^1.0.0" # Display grid with animation
  percent_indicator:            "^3.0.1"
  font_awesome_flutter:         "^9.0.0"
  dio:                          "^4.0.0"
  path_provider:
  flutter_pdfview:              "^1.2.1"
  just_audio:                   "^0.7.0"
  share:                        "^2.0.0" # Share files with others
  flutter_inappwebview:         "^5.0.5" # Open webpage for live stream
  url_launcher:                 "^6.0.0"
  sqflite:                      "^2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: ^0.9.0


flutter_launcher_name:
  name: "خير أمة"

flutter_icons:
  image_path: 'assets/brand/lunch_icon.jpg'
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/brand/
    - assets/langs/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf

    - family: UthmanTahaNaskh
      fonts:
        - asset: assets/fonts/uthman_taha_naskh/Uthman-Taha-Naskh-Regular.ttf
        - asset: assets/fonts/uthman_taha_naskh/Uthman-Taha-Naskh-Bold.ttf

