name: bestnation
description: Best Nation
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  algolia_helper_flutter:       "^0.2.0" # Query record by like
  cloud_firestore:              "^4.8.4"
  dio:                          "^4.0.0" # Make Http request
  firebase_analytics:           "^10.4.4"
  firebase_core:                "^2.15.0"
#  firebase_messaging:           "^14.7.4" # Send notifications
  flutter_inappwebview:         "^5.7.2+3" # Open webpage buttons
  flutter_staggered_animations: "^1.1.1" # Display grid with animation
  flutter_pdfview:              "^1.2.7"
  font_awesome_flutter:         "^10.5.0"
  get:                          "^4.6.5" # State management
  just_audio:                   "^0.9.34" #Play sound
  audio_service:                 "^0.18.12" #Play sound
  path_provider:                "^2.1.0" # Save files on disk
  percent_indicator:            "^4.2.3"
  permission_handler:           "^10.4.3"
  share_plus:                   "^7.1.0" # Share text with outside of app
  sqflite:                      "^2.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: ^0.9.0


flutter_launcher_name:
  name: "خير أمة"

flutter_icons:
  image_path: 'assets/brand/lunch_icon.jpg'
  android: true
  ios: true

flutter:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf

    - family: UthmanTahaNaskh
      fonts:
        - asset: assets/fonts/uthman_taha_naskh/Uthman-Taha-Naskh-Regular.ttf
        - asset: assets/fonts/uthman_taha_naskh/Uthman-Taha-Naskh-Bold.ttf

  uses-material-design: true

  assets:
    - assets/brand/
    - assets/langs/



